name: Build Monarch APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Monarch-System-V2
          path: bin/*.apk
          
